[2025-10-30T04:15:19.732+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_local_pipeline.dbt_run manual__2025-10-30T04:14:48.821390+00:00 [queued]>
[2025-10-30T04:15:19.767+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_local_pipeline.dbt_run manual__2025-10-30T04:14:48.821390+00:00 [queued]>
[2025-10-30T04:15:19.768+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-30T04:15:19.807+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-30 04:14:48.821390+00:00
[2025-10-30T04:15:19.837+0000] {standard_task_runner.py:60} INFO - Started process 3206 to run task
[2025-10-30T04:15:19.853+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_local_pipeline', 'dbt_run', 'manual__2025-10-30T04:14:48.821390+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/dbt_local_dag.py', '--cfg-path', '/tmp/tmp07m24_1h']
[2025-10-30T04:15:19.866+0000] {standard_task_runner.py:88} INFO - Job 293: Subtask dbt_run
[2025-10-30T04:15:20.266+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_local_pipeline.dbt_run manual__2025-10-30T04:14:48.821390+00:00 [running]> on host 257bb6028ed5
[2025-10-30T04:15:20.941+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='winardi' AIRFLOW_CTX_DAG_ID='dbt_local_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T04:14:48.821390+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-30T04:14:48.821390+00:00'
[2025-10-30T04:15:20.973+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-30T04:15:20.987+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            cd /opt/***/include/dbt/dbt_project &&             dbt run --profiles-dir /home/***/.dbt --target dev\n        ']
[2025-10-30T04:15:21.197+0000] {subprocess.py:86} INFO - Output:
[2025-10-30T04:15:35.352+0000] {subprocess.py:93} INFO - [0m04:15:35  Running with dbt=1.9.0-b2
[2025-10-30T04:15:38.901+0000] {subprocess.py:93} INFO - [0m04:15:38  Registered adapter: postgres=1.8.2
[2025-10-30T04:15:46.969+0000] {subprocess.py:93} INFO - [0m04:15:46  Found 5 models, 14 data tests, 1 source, 423 macros
[2025-10-30T04:15:46.985+0000] {subprocess.py:93} INFO - [0m04:15:46
[2025-10-30T04:15:47.042+0000] {subprocess.py:93} INFO - [0m04:15:47  Concurrency: 1 threads (target='dev')
[2025-10-30T04:15:47.044+0000] {subprocess.py:93} INFO - [0m04:15:47
[2025-10-30T04:15:47.886+0000] {subprocess.py:93} INFO - [0m04:15:47  1 of 5 START sql table model datamart.dim_card_holder .......................... [RUN]
[2025-10-30T04:15:50.747+0000] {subprocess.py:93} INFO - [0m04:15:50  1 of 5 OK created sql table model datamart.dim_card_holder ..................... [[32mSELECT 10000[0m in 2.80s]
[2025-10-30T04:15:50.844+0000] {subprocess.py:93} INFO - [0m04:15:50  2 of 5 START sql table model datamart.dim_corridor ............................. [RUN]
[2025-10-30T04:15:53.360+0000] {subprocess.py:93} INFO - [0m04:15:53  2 of 5 OK created sql table model datamart.dim_corridor ........................ [[32mSELECT 221[0m in 2.50s]
[2025-10-30T04:15:53.370+0000] {subprocess.py:93} INFO - [0m04:15:53  3 of 5 START sql table model datamart.dim_stop ................................. [RUN]
[2025-10-30T04:15:55.544+0000] {subprocess.py:93} INFO - [0m04:15:55  3 of 5 OK created sql table model datamart.dim_stop ............................ [[32mSELECT 5851[0m in 2.14s]
[2025-10-30T04:15:55.563+0000] {subprocess.py:93} INFO - [0m04:15:55  4 of 5 START sql table model datamart.dim_time ................................. [RUN]
[2025-10-30T04:16:01.065+0000] {subprocess.py:93} INFO - [0m04:16:01  4 of 5 OK created sql table model datamart.dim_time ............................ [[32mSELECT 27836[0m in 5.49s]
[2025-10-30T04:16:01.071+0000] {subprocess.py:93} INFO - [0m04:16:01  5 of 5 START sql incremental model datamart.fact_transactions .................. [RUN]
[2025-10-30T04:24:20.904+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-10-30T04:24:20.929+0000] {process_utils.py:131} INFO - Sending 15 to group 3206. PIDs of all processes in the group: [3207, 3208, 3210, 3206]
[2025-10-30T04:24:20.932+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 3206
[2025-10-30T04:24:20.937+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-10-30T04:24:20.943+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-10-30T04:24:21.132+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3210, status='terminated', started='04:15:35') (3210) terminated with exit code None
[2025-10-30T04:24:21.227+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3207, status='terminated', started='04:15:20') (3207) terminated with exit code None
[2025-10-30T04:24:21.228+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3208, status='terminated', started='04:15:20') (3208) terminated with exit code None
[2025-10-30T04:24:21.229+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3206, status='terminated', exitcode=0, started='04:15:19') (3206) terminated with exit code 0
