[2025-10-08T14:34:15.508+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_spark_connection.test_spark manual__2025-10-08T14:34:03.234981+00:00 [queued]>
[2025-10-08T14:34:15.547+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_spark_connection.test_spark manual__2025-10-08T14:34:03.234981+00:00 [queued]>
[2025-10-08T14:34:15.548+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-08T14:34:15.589+0000] {taskinstance.py:2191} INFO - Executing <Task(SparkSubmitOperator): test_spark> on 2025-10-08 14:34:03.234981+00:00
[2025-10-08T14:34:15.604+0000] {standard_task_runner.py:60} INFO - Started process 240 to run task
[2025-10-08T14:34:15.613+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_spark_connection', 'test_spark', 'manual__2025-10-08T14:34:03.234981+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/test_spark.py', '--cfg-path', '/tmp/tmpm5tdpyjc']
[2025-10-08T14:34:15.618+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask test_spark
[2025-10-08T14:34:15.733+0000] {task_command.py:423} INFO - Running <TaskInstance: test_spark_connection.test_spark manual__2025-10-08T14:34:03.234981+00:00 [running]> on host a4ca89524e70
[2025-10-08T14:34:15.970+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_spark_connection' AIRFLOW_CTX_TASK_ID='test_spark' AIRFLOW_CTX_EXECUTION_DATE='2025-10-08T14:34:03.234981+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-08T14:34:03.234981+00:00'
[2025-10-08T14:34:15.999+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2025-10-08T14:34:16.005+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://host.docker.internal:7077 --name arrow-spark --verbose /opt/***/dags/pi.py
[2025-10-08T14:34:16.250+0000] {spark_submit.py:488} INFO - JAVA_HOME is not set
[2025-10-08T14:34:16.269+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://host.docker.internal:7077 --name arrow-spark --verbose /opt/***/dags/pi.py. Error code is: 1.
[2025-10-08T14:34:16.280+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_spark_connection, task_id=test_spark, execution_date=20251008T143403, start_date=20251008T143415, end_date=20251008T143416
[2025-10-08T14:34:16.319+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task test_spark (Cannot execute: spark-submit --master spark://host.docker.internal:7077 --name arrow-spark --verbose /opt/***/dags/pi.py. Error code is: 1.; 240)
[2025-10-08T14:34:16.397+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-08T14:34:16.447+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
