[2025-10-23T16:02:46.564+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_csv_to_postgres.spark_load_csv_to_postgres manual__2025-10-23T16:02:31.652918+00:00 [queued]>
[2025-10-23T16:02:46.611+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_csv_to_postgres.spark_load_csv_to_postgres manual__2025-10-23T16:02:31.652918+00:00 [queued]>
[2025-10-23T16:02:46.651+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-23T16:02:46.821+0000] {taskinstance.py:2191} INFO - Executing <Task(SparkSubmitOperator): spark_load_csv_to_postgres> on 2025-10-23 16:02:31.652918+00:00
[2025-10-23T16:02:46.875+0000] {standard_task_runner.py:60} INFO - Started process 436 to run task
[2025-10-23T16:02:46.887+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_csv_to_postgres', 'spark_load_csv_to_postgres', 'manual__2025-10-23T16:02:31.652918+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/dag_csv_to_postgres_dag.py', '--cfg-path', '/tmp/tmpp3t4ahvc']
[2025-10-23T16:02:46.894+0000] {standard_task_runner.py:88} INFO - Job 166: Subtask spark_load_csv_to_postgres
[2025-10-23T16:02:47.042+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_csv_to_postgres.spark_load_csv_to_postgres manual__2025-10-23T16:02:31.652918+00:00 [running]> on host 2ef039423968
[2025-10-23T16:02:47.242+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='winardi' AIRFLOW_CTX_DAG_ID='etl_csv_to_postgres' AIRFLOW_CTX_TASK_ID='spark_load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T16:02:31.652918+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T16:02:31.652918+00:00'
[2025-10-23T16:02:47.294+0000] {spark_submit.py:219} INFO - Could not load connection string spark_conn, defaulting to yarn
[2025-10-23T16:02:47.300+0000] {spark_submit.py:341} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=local[*] --name spark_load_csv_to_postgres --verbose /opt/***/include/scripts/load_csv_to_postgres.py
[2025-10-23T16:03:15.621+0000] {spark_submit.py:492} INFO - Using properties file: null
[2025-10-23T16:03:17.462+0000] {spark_submit.py:492} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-10-23T16:03:17.464+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2025-10-23T16:03:17.539+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2025-10-23T16:03:17.542+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2025-10-23T16:03:17.544+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2025-10-23T16:03:17.545+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2025-10-23T16:03:17.546+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2025-10-23T16:03:17.547+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2025-10-23T16:03:17.548+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2025-10-23T16:03:17.549+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2025-10-23T16:03:17.550+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-10-23T16:03:17.766+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 423, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --name spark_load_csv_to_postgres --verbose /opt/***/include/scripts/load_csv_to_postgres.py. Error code is: 1.
[2025-10-23T16:03:17.848+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_csv_to_postgres, task_id=spark_load_csv_to_postgres, execution_date=20251023T160231, start_date=20251023T160246, end_date=20251023T160317
[2025-10-23T16:03:18.050+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 166 for task spark_load_csv_to_postgres (Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --name spark_load_csv_to_postgres --verbose /opt/***/include/scripts/load_csv_to_postgres.py. Error code is: 1.; 436)
[2025-10-23T16:03:18.137+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-23T16:03:18.340+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
