[2025-10-31T03:21:39.712+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T03:13:24.691114+00:00 [queued]>
[2025-10-31T03:21:39.863+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T03:13:24.691114+00:00 [queued]>
[2025-10-31T03:21:39.865+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-10-31T03:21:39.987+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-31 03:13:24.691114+00:00
[2025-10-31T03:21:40.068+0000] {standard_task_runner.py:60} INFO - Started process 1079 to run task
[2025-10-31T03:21:40.082+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt_pipeline', 'dbt_run', 'manual__2025-10-31T03:13:24.691114+00:00', '--job-id', '352', '--raw', '--subdir', 'DAGS_FOLDER/dbt_local_dag.py', '--cfg-path', '/tmp/tmpo9bnsdpm']
[2025-10-31T03:21:40.089+0000] {standard_task_runner.py:88} INFO - Job 352: Subtask dbt_run
[2025-10-31T03:21:40.261+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T03:13:24.691114+00:00 [running]> on host 257bb6028ed5
[2025-10-31T03:21:40.869+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='winardi' AIRFLOW_CTX_DAG_ID='dag_dbt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T03:13:24.691114+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T03:13:24.691114+00:00'
[2025-10-31T03:21:40.876+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T03:21:40.887+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            cd /opt/***/include/dbt/dbt_project &&             dbt run --profiles-dir /home/***/.dbt --target dev\n        ']
[2025-10-31T03:21:40.924+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T03:21:58.013+0000] {subprocess.py:93} INFO - [0m03:21:58  Running with dbt=1.9.0-b2
[2025-10-31T03:22:00.795+0000] {subprocess.py:93} INFO - [0m03:22:00  Registered adapter: postgres=1.8.2
[2025-10-31T03:22:13.730+0000] {subprocess.py:93} INFO - [0m03:22:13  Found 5 models, 16 data tests, 1 source, 423 macros
[2025-10-31T03:22:13.744+0000] {subprocess.py:93} INFO - [0m03:22:13
[2025-10-31T03:22:13.753+0000] {subprocess.py:93} INFO - [0m03:22:13  Concurrency: 1 threads (target='dev')
[2025-10-31T03:22:13.809+0000] {subprocess.py:93} INFO - [0m03:22:13
[2025-10-31T03:22:15.522+0000] {subprocess.py:93} INFO - [0m03:22:15  1 of 5 START sql table model datamart.dim_card_holder .......................... [RUN]
[2025-10-31T03:22:20.403+0000] {subprocess.py:93} INFO - [0m03:22:20  1 of 5 OK created sql table model datamart.dim_card_holder ..................... [[32mSELECT 10000[0m in 4.87s]
[2025-10-31T03:22:20.418+0000] {subprocess.py:93} INFO - [0m03:22:20  2 of 5 START sql table model datamart.dim_corridor ............................. [RUN]
[2025-10-31T03:22:23.249+0000] {subprocess.py:93} INFO - [0m03:22:23  2 of 5 OK created sql table model datamart.dim_corridor ........................ [[32mSELECT 221[0m in 2.82s]
[2025-10-31T03:22:23.279+0000] {subprocess.py:93} INFO - [0m03:22:23  3 of 5 START sql table model datamart.dim_stop ................................. [RUN]
[2025-10-31T03:22:25.220+0000] {subprocess.py:93} INFO - [0m03:22:25  3 of 5 OK created sql table model datamart.dim_stop ............................ [[32mSELECT 5851[0m in 1.93s]
[2025-10-31T03:22:25.245+0000] {subprocess.py:93} INFO - [0m03:22:25  4 of 5 START sql table model datamart.dim_time ................................. [RUN]
[2025-10-31T03:22:30.110+0000] {subprocess.py:93} INFO - [0m03:22:30  4 of 5 OK created sql table model datamart.dim_time ............................ [[32mSELECT 27836[0m in 4.85s]
[2025-10-31T03:22:30.136+0000] {subprocess.py:93} INFO - [0m03:22:30  5 of 5 START sql incremental model datamart.fact_transactions .................. [RUN]
[2025-10-31T03:34:43.227+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-10-31T03:34:43.787+0000] {process_utils.py:131} INFO - Sending 15 to group 1079. PIDs of all processes in the group: [1080, 1081, 1083, 1079]
[2025-10-31T03:34:43.836+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1079
[2025-10-31T03:34:44.579+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-10-31T03:34:45.141+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-10-31T03:34:45.953+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1081, status='terminated', started='03:21:40') (1081) terminated with exit code None
[2025-10-31T03:34:51.122+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1083, status='terminated', started='03:21:59') (1083) terminated with exit code None
[2025-10-31T03:35:00.145+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1080, status='terminated', started='03:21:40') (1080) terminated with exit code None
[2025-10-31T03:35:00.153+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1079, status='terminated', exitcode=0, started='03:21:39') (1079) terminated with exit code 0
