[2025-10-17T08:31:05.174+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: test_spark_connection.test_spark manual__2025-10-17T08:30:35.327877+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
